module.exports = {
  STRIPE_SECRET: process.env.STRIPE_SECRET,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  JAZZCASH_MERCHANT_ID: process.env.JAZZCASH_MERCHANT_ID,
  JAZZCASH_PASSWORD: process.env.JAZZCASH_PASSWORD,
  JAZZCASH_INTEGERITY_SALT: process.env.JAZZCASH_INTEGERITY_SALT,
};
