// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZh78YSljhGD8nZqmpdEF_Xbt6B4uc9Aw',
    appId: '1:817904341442:web:a7c3dcbec8eba5adee065b',
    messagingSenderId: '817904341442',
    projectId: 'pizza-hub-vehari',
    authDomain: 'pizza-hub-vehari.firebaseapp.com',
    storageBucket: 'pizza-hub-vehari.firebasestorage.app',
    measurementId: 'G-0LSV9Y4RND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDecEs4ql9moIyK9JoLAXsmnCJUAOEhdCA',
    appId: '1:817904341442:android:364ae532e54b97e4ee065b',
    messagingSenderId: '817904341442',
    projectId: 'pizza-hub-vehari',
    storageBucket: 'pizza-hub-vehari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFLme57-EW9YmtaT6yOOdaOziCEwO_EJo',
    appId: '1:817904341442:ios:d4faffc32a374e2eee065b',
    messagingSenderId: '817904341442',
    projectId: 'pizza-hub-vehari',
    storageBucket: 'pizza-hub-vehari.firebasestorage.app',
    androidClientId: '817904341442-uaejh9qt5q8avms0h39kev7j4dguf9s4.apps.googleusercontent.com',
    iosClientId: '817904341442-ip7u4kb6qiq5mrs2un7mroeot23vo0g8.apps.googleusercontent.com',
    iosBundleId: 'pk.vehari.pizzahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFLme57-EW9YmtaT6yOOdaOziCEwO_EJo',
    appId: '1:817904341442:ios:15510ae5d069a8ccee065b',
    messagingSenderId: '817904341442',
    projectId: 'pizza-hub-vehari',
    storageBucket: 'pizza-hub-vehari.firebasestorage.app',
    androidClientId: '817904341442-uaejh9qt5q8avms0h39kev7j4dguf9s4.apps.googleusercontent.com',
    iosClientId: '817904341442-n8raqgol8is94i7k6il62asg7vie62bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMultiRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZh78YSljhGD8nZqmpdEF_Xbt6B4uc9Aw',
    appId: '1:817904341442:web:4fa3db4ac79c93d9ee065b',
    messagingSenderId: '817904341442',
    projectId: 'pizza-hub-vehari',
    authDomain: 'pizza-hub-vehari.firebaseapp.com',
    storageBucket: 'pizza-hub-vehari.firebasestorage.app',
    measurementId: 'G-MXVM592MCR',
  );

}
